generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Producto
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          producto
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        codigo: {label: Codigo}
        precio_vta: { label: Precio de Venta, help: Es el precio de venta del producto y el que se toma como referencia en la lista de precio}
        grupoprod_id: { label: Grupo}
        minimo_stock: { label: Stock Minimo}
        orden_grupo: { label: Orden, help: Es un numero para los productos se vean ordendos en el grupo}
        activo: { label: Activo, help: Indica si el producto se puede utilizar o no}
      list:
        table_method: retrieveProdConGrupo
        title: Administraci&oacute;n de Productos
        sort: [nombre, asc]
        display: [Grupo, nombre, _precio_venta, minimo_stock, orden_grupo, activo, lista_id, _foto]
        object_actions:
          _delete: {label: Eliminar}
          _edit: {label: Modificar}
        actions:
          _new: {label: Nuevo}
          imprimir: {label: Imprimir}
          lista: {label: Lista de Precios}
        batch_actions:
          _delete: {label: Eliminar}
          desactivar: ~
          activar: ~
          precio: {label: Cambiar Precio}
      filter:  ~
      form:
        display: [grupoprod_id, codigo, nombre, foto, precio_vta, iva, total, minimo_stock, orden_grupo, activo, lista_id]
      edit:
        title: Modificar Producto
      new:
        title: Nuevo Producto
