generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ClienteSeguimiento
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          cliente_seguimiento
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        fecha: { date_format: dd/MM/yyyy }
        prox_contac_fecha: {label: Prox. Fecha, date_format: dd/MM/yyyy}
        prox_contac_hora: {label: Prox. Hora}
        TipoTiempoContac: {label: Prox. Tiempo}
        prox_contact_coment: {label: Comentario}
        TipoMotivo: {label: Motivo del Contacto}
        motivo_id: {label: Motivo del Contacto}
        TipoContacto: {label: Medio de Contacto}
        tipo_contacto_id: {label: Medio de Contacto}
        TipoRespuesta: {label: Respuesta}
        tipo_respuesta_id: {label: Respuesta}
        realizada: {label: Hecho}
      list:
        title: Seguimiento de Clientes
        display: [Cliente, TipoMotivo, fecha, hora, TipoContacto, TipoRespuesta, comentario, prox_contac_fecha, prox_contac_hora, prox_contact_coment, realizada]
        object_actions:
          _delete: {label: Eliminar}
          _hecho: {label: Hecho}
        actions:
          _new: ~
          imprimir: {label: Imprimir}        
      filter:
        display: [cliente_id, motivo_id, fecha, hora, tipo_contacto_id, tipo_respuesta_id, prox_contac_fecha, prox_contac_hora, realizada]
      form: ~
      edit:    ~
      new:
        title: Nuevo Conctacto a Cliente
        display: [cliente_id, motivo_id, fecha, hora, tipo_contacto_id, tipo_respuesta_id, realizada, comentario, prox_contac_fecha, prox_contac_hora, prox_contact_coment]
