generator:
  class: sfDoctrineGenerator
  param:
    model_class:           DetallePresupuesto
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          detalle_presupuesto
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      fields: ~
      list:
        table_method: retrieveConJoins
        title: Detalle del presupuesto
        display: [Producto, _precio, cantidad, _iva, _total]
        object_actions:
          _delete: {label: Eliminar}
          _edit: {label: Modificar}
        actions:
          _new: {label: Nuevo}
          imprimir: {label: Imprimir}
      filter: {}
      form: ~
      edit:
        title: Modificar detalle del presupuesto
      new:
        title: Nuevo detalle del presupuesto