<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('compra2', 'doctrine');

/**
 * Basecompra2
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $numero
 * @property integer $proveedor_id
 * @property date $fecha
 * @property integer $producto_id
 * @property integer $cantidad
 * @property string $nro_lote
 * @property Proveedor $Proveedor
 * @property Producto2 $Producto2
 * 
 * @method integer   getId()            Returns the current record's "id" value
 * @method integer   getNumero()  Returns the current record's "numero_compra" value
 * @method integer   getProveedorId()   Returns the current record's "proveedor_id" value
 * @method date      getFecha()         Returns the current record's "fecha" value
 * @method integer   getProductoId()    Returns the current record's "producto_id" value
 * @method integer   getCantidad()      Returns the current record's "cantidad" value
 * @method string    getNroLote()       Returns the current record's "nro_lote" value
 * @method Proveedor getProveedor()     Returns the current record's "Proveedor" value
 * @method Producto2 getProducto2()     Returns the current record's "Producto2" value
 * @method compra2   setId()            Sets the current record's "id" value
 * @method compra2   setNumeroCompra()  Sets the current record's "numero_compra" value
 * @method compra2   setProveedorId()   Sets the current record's "proveedor_id" value
 * @method compra2   setFecha()         Sets the current record's "fecha" value
 * @method compra2   setProductoId()    Sets the current record's "producto_id" value
 * @method compra2   setCantidad()      Sets the current record's "cantidad" value
 * @method compra2   setNroLote()       Sets the current record's "nro_lote" value
 * @method compra2   setProveedor()     Sets the current record's "Proveedor" value
 * @method compra2   setProducto2()     Sets the current record's "Producto2" value
 * 
 * @package    odontopc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecompra2 extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('compra2');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('numero', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('proveedor_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'length' => 25,
             ));
        $this->hasColumn('producto_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('cantidad', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('nro_lote', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Proveedor', array(
             'local' => 'proveedor_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Producto2', array(
             'local' => 'producto_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));
    }
}