<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Cuenta', 'doctrine');

/**
 * BaseCuenta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property Doctrine_Collection $Compra
 * 
 * @method integer             getId()     Returns the current record's "id" value
 * @method string              getNombre() Returns the current record's "nombre" value
 * @method Doctrine_Collection getCompra() Returns the current record's "Compra" collection
 * @method Cuenta              setId()     Sets the current record's "id" value
 * @method Cuenta              setNombre() Sets the current record's "nombre" value
 * @method Cuenta              setCompra() Sets the current record's "Compra" collection
 * 
 * @package    odontopc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCuenta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cuenta_compras');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Compra', array(
             'local' => 'id',
             'foreign' => 'cuenta_id'));
    }
}