<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PromocionRegalo', 'doctrine');

/**
 * BasePromocionRegalo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $promocion_id
 * @property integer $producto_id
 * @property Promocion $Promocion
 * @property Producto $Producto
 * 
 * @method integer         getId()           Returns the current record's "id" value
 * @method integer         getPromocionId()  Returns the current record's "promocion_id" value
 * @method integer         getProductoId()   Returns the current record's "producto_id" value
 * @method Promocion       getPromocion()    Returns the current record's "Promocion" value
 * @method Producto        getProducto()     Returns the current record's "Producto" value
 * @method PromocionRegalo setId()           Sets the current record's "id" value
 * @method PromocionRegalo setPromocionId()  Sets the current record's "promocion_id" value
 * @method PromocionRegalo setProductoId()   Sets the current record's "producto_id" value
 * @method PromocionRegalo setPromocion()    Sets the current record's "Promocion" value
 * @method PromocionRegalo setProducto()     Sets the current record's "Producto" value
 * 
 * @package    odontopc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePromocionRegalo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('promocion_regalo');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('promocion_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('producto_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Promocion', array(
             'local' => 'promocion_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Producto', array(
             'local' => 'producto_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));
    }
}