<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ClienteUltimaCompra', 'doctrine');

/**
 * BaseClienteUltimaCompra
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $zona_id
 * @property string $apellido
 * @property string $nombre
 * @property string $telefono
 * @property string $email
 * @property string $celular
 * @property date $fecha
 * @property integer $resumen_id
 * @property Zona $Zona
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method integer             getZonaId()     Returns the current record's "zona_id" value
 * @method string              getApellido()   Returns the current record's "apellido" value
 * @method string              getNombre()     Returns the current record's "nombre" value
 * @method string              getTelefono()   Returns the current record's "telefono" value
 * @method string              getEmail()      Returns the current record's "email" value
 * @method string              getCelular()    Returns the current record's "celular" value
 * @method date                getFecha()      Returns the current record's "fecha" value
 * @method integer             getResumenId()  Returns the current record's "resumen_id" value
 * @method Zona                getZona()       Returns the current record's "Zona" value
 * @method ClienteUltimaCompra setId()         Sets the current record's "id" value
 * @method ClienteUltimaCompra setZonaId()     Sets the current record's "zona_id" value
 * @method ClienteUltimaCompra setApellido()   Sets the current record's "apellido" value
 * @method ClienteUltimaCompra setNombre()     Sets the current record's "nombre" value
 * @method ClienteUltimaCompra setTelefono()   Sets the current record's "telefono" value
 * @method ClienteUltimaCompra setEmail()      Sets the current record's "email" value
 * @method ClienteUltimaCompra setCelular()    Sets the current record's "celular" value
 * @method ClienteUltimaCompra setFecha()      Sets the current record's "fecha" value
 * @method ClienteUltimaCompra setResumenId()  Sets the current record's "resumen_id" value
 * @method ClienteUltimaCompra setZona()       Sets the current record's "Zona" value
 * 
 * @package    odontopc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClienteUltimaCompra extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cliente_ultima_compra');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('zona_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('apellido', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('nombre', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('telefono', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('email', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('celular', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'length' => 25,
             ));
        $this->hasColumn('resumen_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Zona', array(
             'local' => 'zona_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));
    }
}