<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Parametros', 'doctrine');

/**
 * BaseParametros
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $valor
 * 
 * @method integer    getId()     Returns the current record's "id" value
 * @method string     getNombre() Returns the current record's "nombre" value
 * @method string     getValor()  Returns the current record's "valor" value
 * @method Parametros setId()     Sets the current record's "id" value
 * @method Parametros setNombre() Sets the current record's "nombre" value
 * @method Parametros setValor()  Sets the current record's "valor" value
 * 
 * @package    odontopc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseParametros extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('parametros');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('valor', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}