<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DetLisPrecio', 'doctrine');

/**
 * BaseDetLisPrecio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $lista_id
 * @property integer $producto_id
 * @property integer $grupoprod_id
 * @property integer $aumento
 * @property integer $descuento
 * @property decimal $precio
 * @property ListaPrecio $Lista
 * @property Producto $Producto
 * @property Grupoprod $Grupo
 * 
 * @method integer      getId()           Returns the current record's "id" value
 * @method integer      getListaId()      Returns the current record's "lista_id" value
 * @method integer      getProductoId()   Returns the current record's "producto_id" value
 * @method integer      getGrupoprodId()  Returns the current record's "grupoprod_id" value
 * @method integer      getAumento()      Returns the current record's "aumento" value
 * @method integer      getDescuento()    Returns the current record's "descuento" value
 * @method decimal      getPrecio()       Returns the current record's "precio" value
 * @method ListaPrecio  getLista()        Returns the current record's "Lista" value
 * @method Producto     getProducto()     Returns the current record's "Producto" value
 * @method Grupoprod    getGrupo()        Returns the current record's "Grupo" value
 * @method DetLisPrecio setId()           Sets the current record's "id" value
 * @method DetLisPrecio setListaId()      Sets the current record's "lista_id" value
 * @method DetLisPrecio setProductoId()   Sets the current record's "producto_id" value
 * @method DetLisPrecio setGrupoprodId()  Sets the current record's "grupoprod_id" value
 * @method DetLisPrecio setAumento()      Sets the current record's "aumento" value
 * @method DetLisPrecio setDescuento()    Sets the current record's "descuento" value
 * @method DetLisPrecio setPrecio()       Sets the current record's "precio" value
 * @method DetLisPrecio setLista()        Sets the current record's "Lista" value
 * @method DetLisPrecio setProducto()     Sets the current record's "Producto" value
 * @method DetLisPrecio setGrupo()        Sets the current record's "Grupo" value
 * 
 * @package    odontopc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDetLisPrecio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('det_lis_precio');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('lista_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('producto_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('grupoprod_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('aumento', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('descuento', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('precio', 'decimal', 10, array(
             'type' => 'decimal',
             'length' => 10,
             'scale' => '2',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ListaPrecio as Lista', array(
             'local' => 'lista_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Producto', array(
             'local' => 'producto_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Grupoprod as Grupo', array(
             'local' => 'grupoprod_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));
    }
}