<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ListadoCompras', 'doctrine');

/**
 * BaseListadoCompras
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $compra_id
 * @property date $fecha
 * @property integer $proveedor_id
 * @property integer $producto_id
 * @property decimal $precio
 * @property integer $cantidad
 * @property decimal $total
 * @property integer $grupoprod_id
 * @property string $nro_lote
 * @property integer $zona_id
 * @property DetalleCompra $DetalleCompra
 * @property Compra $Compra
 * @property Proveedor $Proveedor
 * @property Producto $Producto
 * @property Grupoprod $Grupo
 * @property Zona $Zona
 * 
 * @method integer        getId()            Returns the current record's "id" value
 * @method integer        getCompraId()      Returns the current record's "compra_id" value
 * @method date           getFecha()         Returns the current record's "fecha" value
 * @method integer        getProveedorId()   Returns the current record's "proveedor_id" value
 * @method integer        getProductoId()    Returns the current record's "producto_id" value
 * @method decimal        getPrecio()        Returns the current record's "precio" value
 * @method integer        getCantidad()      Returns the current record's "cantidad" value
 * @method decimal        getTotal()         Returns the current record's "total" value
 * @method integer        getGrupoprodId()   Returns the current record's "grupoprod_id" value
 * @method string         getNroLote()       Returns the current record's "nro_lote" value
 * @method integer        getZonaId()        Returns the current record's "zona_id" value
 * @method DetalleCompra  getDetalleCompra() Returns the current record's "DetalleCompra" value
 * @method Compra         getCompra()        Returns the current record's "Compra" value
 * @method Proveedor      getProveedor()     Returns the current record's "Proveedor" value
 * @method Producto       getProducto()      Returns the current record's "Producto" value
 * @method Grupoprod      getGrupo()         Returns the current record's "Grupo" value
 * @method Zona           getZona()          Returns the current record's "Zona" value
 * @method ListadoCompras setId()            Sets the current record's "id" value
 * @method ListadoCompras setCompraId()      Sets the current record's "compra_id" value
 * @method ListadoCompras setFecha()         Sets the current record's "fecha" value
 * @method ListadoCompras setProveedorId()   Sets the current record's "proveedor_id" value
 * @method ListadoCompras setProductoId()    Sets the current record's "producto_id" value
 * @method ListadoCompras setPrecio()        Sets the current record's "precio" value
 * @method ListadoCompras setCantidad()      Sets the current record's "cantidad" value
 * @method ListadoCompras setTotal()         Sets the current record's "total" value
 * @method ListadoCompras setGrupoprodId()   Sets the current record's "grupoprod_id" value
 * @method ListadoCompras setNroLote()       Sets the current record's "nro_lote" value
 * @method ListadoCompras setZonaId()        Sets the current record's "zona_id" value
 * @method ListadoCompras setDetalleCompra() Sets the current record's "DetalleCompra" value
 * @method ListadoCompras setCompra()        Sets the current record's "Compra" value
 * @method ListadoCompras setProveedor()     Sets the current record's "Proveedor" value
 * @method ListadoCompras setProducto()      Sets the current record's "Producto" value
 * @method ListadoCompras setGrupo()         Sets the current record's "Grupo" value
 * @method ListadoCompras setZona()          Sets the current record's "Zona" value
 * 
 * @package    odontopc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseListadoCompras extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('listado_compras');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('compra_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('proveedor_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('producto_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('precio', 'decimal', 10, array(
             'type' => 'decimal',
             'length' => 10,
             'scale' => '2',
             ));
        $this->hasColumn('cantidad', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('total', 'decimal', 10, array(
             'type' => 'decimal',
             'length' => 10,
             'scale' => '2',
             ));
        $this->hasColumn('grupoprod_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('nro_lote', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('zona_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DetalleCompra', array(
             'local' => 'id',
             'foreign' => 'id'));

        $this->hasOne('Compra', array(
             'local' => 'compra_id',
             'foreign' => 'id'));

        $this->hasOne('Proveedor', array(
             'local' => 'proveedor_id',
             'foreign' => 'id'));

        $this->hasOne('Producto', array(
             'local' => 'producto_id',
             'foreign' => 'id'));

        $this->hasOne('Grupoprod as Grupo', array(
             'local' => 'grupoprod_id',
             'foreign' => 'id'));

        $this->hasOne('Zona', array(
             'local' => 'zona_id',
             'foreign' => 'id'));
    }
}