<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ClienteUltimaCompra', 'doctrine');

/**
 * BaseClienteUltimaCompra
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $cliente_id
 * @property string $apellido
 * @property string $nombre
 * @property date $fecha
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method integer             getClienteId()  Returns the current record's "cliente_id" value
 * @method string              getApellido()   Returns the current record's "apellido" value
 * @method string              getNombre()     Returns the current record's "nombre" value
 * @method date                getFecha()      Returns the current record's "fecha" value
 * @method ClienteUltimaCompra setId()         Sets the current record's "id" value
 * @method ClienteUltimaCompra setClienteId()  Sets the current record's "cliente_id" value
 * @method ClienteUltimaCompra setApellido()   Sets the current record's "apellido" value
 * @method ClienteUltimaCompra setNombre()     Sets the current record's "nombre" value
 * @method ClienteUltimaCompra setFecha()      Sets the current record's "fecha" value
 * 
 * @package    odontopc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClienteUltimaCompra extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cliente_ultima_compra');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('cliente_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('apellido', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('nombre', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}