generator:
  class: sfDoctrineGenerator
  param:
    model_class:           DetalleCompra
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          detalle_compra
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        fecha_vto: { date_format: dd/MM/yyyy }
        tiene_vto: {label: Tiene Vto}
        trazable: {help: Esto indica si el lote va a salir en el listado de traza}
      list:
        title: Detalle de Compra
        max_per_page: 999
        display: [Compra, Producto, nro_lote, fecha_vto, cantidad]
        object_actions:
          _delete: ~
        batch_actions: {}       
        actions:
          _new: {label: Nuevo}
          imprimir: {label: Imprimir}
      filter:  ~
      form:    ~
      edit:
        title: Modificar Detalle de la compra %%Compra%%
      new:
        title: Nuevo Detalle de la compra %%Compra%%
        display: [producto_id, trazable, nro_lote, tiene_vto, fecha_vto, cantidad, observacion]
