generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Producto2
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          producto2
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Productos para Trazar
        display: [Grupo, codigo, nombre]
        object_actions:
          _delete: {label: Eliminar}
          _edit: {label: Modificar}
      filter:  ~
      form:    ~
      edit:
        title: Modificar producto
      new:
        title: Nuevo producto
