generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Presupuesto
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          presupuesto
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        id: {label: Nro}
        fecha: { date_format: dd/MM/yyyy }
        descripcion: {label: Presupuesto a nombre de}
      list:
        table_method: retrieveConJoins
        title: Administracion Presupuestos
        display: [id, fecha, descripcion, email, telefono]
        actions:
          _new: {label: Nuevo}
        object_actions:
          _delete: {label: Borrar}
          _edit: {label: Modificar}
          detalle: {label: Ver Detalle}
          imprimir: ~
          mail: ~
      filter:
        display: [id, fecha]
      form:
        actions:
          _list: {label: Volver}
          _save: {label: 'Guardar y Agregar Detalle'}
      edit:
        title: Modificar Presupuesto
      new:
        title: Nuevo Presupuesto