<?php

/**
 * ClienteSaldoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClienteSaldoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClienteSaldoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClienteSaldo');
    }
		
  static public function applyMayorFilter($query, $value)
  {
    $rootAlias = $query->getRootAlias();
    $query->where($rootAlias.'.saldo > '.$value);
    return $query;
  }		
}