<?php

/**
 * ClienteSeguimientoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClienteSeguimientoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClienteSeguimientoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClienteSeguimiento');
    }
}