<?php

/**
 * ClienteDomicilioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClienteDomicilioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClienteDomicilioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClienteDomicilio');
    }
}