<?php

/**
 * ClienteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClienteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClienteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cliente');
    }
    
    public function retrieveConJoins(Doctrine_Query $q){
      $rootAlias = $q->getRootAlias();
      $q->leftJoin($rootAlias . '.Tipo t');
      $q->leftJoin($rootAlias . '.Localidad l');
      return $q;
    }
    
    public function retrieveConSaldos(Doctrine_Query $q){
      $rootAlias = $q->getRootAlias();
      $q->addSelect('t.nombre');
      $q->addSelect('m.nombre');
      $q->addSelect($rootAlias . '.dni');
      $q->addSelect($rootAlias . '.apellido');
      $q->addSelect($rootAlias . '.nombre');
      $q->addSelect('FORMAT(sum(cta.debe - cta.haber), 2) as saldo');
      $q->addSelect('cta.id');
      $q->addSelect('m.simbolo as simbolo');
      $q->leftJoin($rootAlias . '.Cuenta cta');
      $q->leftJoin($rootAlias . '.Tipo t');
      $q->leftJoin('cta.Moneda m');
      $q->addGroupBy('t.nombre');
      $q->addGroupBy('m.nombre');
      $q->addGroupBy($rootAlias . '.dni');
      $q->addGroupBy($rootAlias . '.apellido');
      $q->addGroupBy($rootAlias . '.nombre');
      $q->orderBy($rootAlias . '.apellido asc');
      $q->addOrderBy($rootAlias . '.nombre asc');
      return $q;
    }
    
    public function retrieveConSaldosCount(Doctrine_Query $q){
      //$rootAlias = $q->getRootAlias();
      return $q;
    }
    
    public function findClientexNombre($name, $limit=10){
      return Doctrine_Core::getTable('Cliente')
      ->createQuery('c')
	  ->select('id, concat(apellido, " ", nombre) as ayn')
      ->where("c.apellido LIKE '%$name%'")
      ->limit($limit)
      ->execute();
    }
	
	public function getActivos(){
		$query = Doctrine_Core::getTable('Cliente')
		->createQuery('q')
		->where('q.activo = ?', '1')
		->orderBy('apellido ASC, nombre ASC');
		$result = $query->execute();
		return $result;
	}	
}