<?php

/**
 * CobroResumenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CobroResumenTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CobroResumenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CobroResumen');
    }
}