<?php

/**
 * CobroTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CobroTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CobroTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cobro');
    }
    
    public function retrieveConJoins(Doctrine_Query $q){
		$id = sfContext::getInstance()->getUser()->getGuardUser()->getId();
		$rootAlias = $q->getRootAlias();
		$q->leftJoin($rootAlias . '.Cliente c');
		$q->leftJoin('c.Zona z');
		$q->leftJoin('z.UsuarioZona uz');
		$q->where($rootAlias . '.tipo_id <> 5');
		$q->orderBy($rootAlias . '.fecha desc');
		return $q;
    }    
}