<?php

/**
 * CompraTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompraTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CompraTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Compra');
    }
    
    function construct(){
        $this->setOption('orderBy','fecha DESC');
    }    
    public function retrieveConJoins(Doctrine_Query $q){
      $rootAlias = $q->getRootAlias();
      $q->leftJoin($rootAlias . '.Proveedor p');
      $q->leftJoin($rootAlias . '.Tipofactura tf');
      $q->orderBy($rootAlias . '.fecha desc');
      return $q;
    }
}