<?php

/**
 * Compra
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    odontopc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Compra extends BaseCompra
{
  public function __toString()
  {
        return 'Nro: '.$this->getNumero();//.' - Fecha: '.$this->getFecha();
  }
  
  public function SimboloMoneda(){
    return $this->getMoneda()->getSimbolo();
  }
  
  public function getTotal()
  {
    $suma = 0;
    foreach($this->getDetalles() as $det){
      $suma += $det->getTotal();
    }
    return $suma;
  }  
  
  public function TotalFormato(){
    return sprintf($this->SimboloMoneda()." %01.2f", $this->getTotal());
  } 
  
  public function getTotalPagado(){
    $suma = 0;
    foreach($this->getPagoCompra() as $pago){
      $suma += $pago->getMonto();
    }
    return $suma;
  }
}