<?php

/**
 * CondicionFiscalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CondicionFiscalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CondicionFiscalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CondicionFiscal');
    }
}