<?php

/**
 * ControlStock
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    odontopc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ControlStock extends BaseControlStock
{
	function getCantVendida()
	{
		return (empty($this->cant_vendida))? 0:$this->cant_vendida;
	}
	
	function getStock()
	{
		return (empty($this->stock))? 0:$this->stock;
	}	
}