<?php

/**
 * ControlStockTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ControlStockTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ControlStockTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ControlStock');
    }
}