<?php

/**
 * CtaCteProvTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CtaCteProvTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CtaCteProvTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CtaCteProv');
    }
    
    public function retrieveCtaConProv(Doctrine_Query $q){
      $rootAlias = $q->getRootAlias();
      $q->leftJoin($rootAlias . '.Proveedor p');
      $q->orderBy('fecha');
      return $q;
    } 
}