<?php

/**
 * CtaCteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CtaCteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CtaCteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CtaCte');
    }
    
    public function retrieveCtaConCli(Doctrine_Query $q){
      $rootAlias = $q->getRootAlias();
      $q->leftJoin($rootAlias . '.Cliente c');
      $q->orderBy('fecha');
      return $q;
    }    
}