<?php

/**
 * Curso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    odontopc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Curso extends BaseCurso
{
  public function __toString(){
    $val = $this->getNombre();
    return empty($val)? '' : $val;
  }
  
  public function InscripcionDesdeHasta(){
    $inicio = implode('/', array_reverse(explode('-', $this->getIniInsc())));
    $fin = implode('/', array_reverse(explode('-', $this->getFinInsc())));
    return 'Desde el '.$inicio.' al '.$fin;
  }
  
  public function hayActivos(){
    $q = Doctrine_Query::create()->select('count(id) as cuenta')->from('Curso c')->where('habilitado = ?', 'SI');
    $cuenta = $q->execute();
    if($cuenta[0]['cuenta'] > 0)
      return true;
    else
      return false;
  }
  
  public function DesactivarOtros(){
	$table = Doctrine::getTable('Curso');
    $table->createQuery()->update()->set('habilitado', "'NO'")->where('id <> ?', $this->getId())->execute();
  }  
  
}