<?php

/**
 * CursoInscripcionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CursoInscripcionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CursoInscripcionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CursoInscripcion');
    }
}