<?php

/**
 * DetalleVentaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DetalleVentaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DetalleVentaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DetalleVenta');
    } 
}