<?php

/**
 * DetallePresupuestoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DetallePresupuestoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DetallePresupuestoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DetallePresupuesto');
    }
    
  public function retrieveConJoins(Doctrine_Query $q){
    $rootAlias = $q->getRootAlias();
    $q->leftJoin($rootAlias . '.Presupuesto pres');
    $q->leftJoin($rootAlias . '.Producto p');
    return $q;
  }
}