<?php

/**
 * DetalleResumenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DetalleResumenTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object DetalleResumenTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('DetalleResumen');
  }
  
  public function retrieveConJoins(Doctrine_Query $q){
    $rootAlias = $q->getRootAlias();
    $q->leftJoin($rootAlias . '.Resumen res');
    $q->leftJoin($rootAlias . '.Producto p');
    $q->leftJoin($rootAlias . '.Lote l');
    return $q;
  }
}