<?php

/**
 * DetalleResumen
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    odontopc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class DetalleResumen extends BaseDetalleResumen
{
	public function setUp()
  {
		parent::setUp();
		$this->hasOne('Lote', array(
		 'local' => 'nro_lote',
		 'foreign' => 'nro_lote',
		 'onDelete' => 'RESTRICT'));
	}
	
  public function SimboloMoneda(){
    return $this->getMoneda()->getSimbolo();
  }
  
  public function PrecioFormato(){
    return sprintf($this->SimboloMoneda()." %01.2f", $this->getPrecio());
  }
  
  public function TotalFormato(){
    return sprintf($this->SimboloMoneda()." %01.2f", $this->getTotal());
  } 
  
  public function IvaFormato(){
    return sprintf($this->SimboloMoneda()." %01.2f", $this->getIva());
  } 
  
  public function SubTotalFormato(){
    return sprintf($this->SimboloMoneda()." %01.2f", $this->getSubTotal());
  }
	
	public function RemitoProductoCantVend(){
		$sql = "
			select 
				sum(cantidad)+
				sum(bonificados)-
				coalesce((select sum(cantidad) 
				from dev_producto 
				where dev_producto.resumen_id = detalle_resumen.resumen_id 
					and dev_producto.producto_id = detalle_resumen.producto_id 
					and dev_producto.nro_lote = detalle_resumen.nro_lote), 0) as total
			from detalle_resumen
			where det_remito_id =".$this->id;
		$con = Doctrine_Manager::getInstance()->connection();
		$st = $con->execute($sql);
		$resultado = $st->fetchAll();
		return $resultado[0]['total'];
	}
}