<?php

/**
 * DetLisPrecio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    odontopc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class DetLisPrecio extends BaseDetLisPrecio
{
  public function getPrecioDetLista($p_precio_prod){
    if($this->getPrecio() != ''){
      $precio_real = $this->getPrecio();
    }elseif($this->getAumento() != ''){
      $aumento = ($this->getAumento()*$p_precio_prod)/100;
      $precio_real = $p_precio_prod + $aumento;
    }elseif($this->getDescuento() != ''){
      $descuento = ($this->getDescuento()*$p_precio_prod)/100;
      $precio_real = $p_precio_prod - $descuento;
    }else{
      $precio_real = $p_precio_prod;
    }
    return $precio_real;
  }
}