<?php

/**
 * EnvioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EnvioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EnvioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Envio');
    }
}