<?php

/**
 * Grupoprod2Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Grupoprod2Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Grupoprod2Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Grupoprod2');
    }
}