<?php

/**
 * ListadoComprasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ListadoComprasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ListadoComprasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ListadoCompras');
    }
    
    public function retrieveConJoins(Doctrine_Query $q){
			$id = sfContext::getInstance()->getUser()->getGuardUser()->getId();
			
			$rootAlias = $q->getRootAlias();
			$q->leftJoin($rootAlias . '.Zona z');
			$q->leftJoin('z.UsuarioZona uz');	
			$q->where('uz.usuario = '.$id);
			$q->andWhere($rootAlias . ".nro_lote not like 'er%'");
			$q->andWhere($rootAlias . ".proveedor_id not in (13, 6)");
      $q->orderBy($rootAlias . '.fecha desc');
			return $q;
    }
}