<?php

/**
 * ListadoCobrosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ListadoCobrosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ListadoCobrosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ListadoCobros');
    }
}