<?php

/**
 * LoteAjusteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LoteAjusteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LoteAjusteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LoteAjuste');
    }
}