<?php

/**
 * LoteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LoteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LoteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Lote');
    }
    
    public function retrieveConJoins(Doctrine_Query $q){
      $rootAlias = $q->getRootAlias();
      $q->leftJoin($rootAlias . '.Producto p');
      $q->leftJoin($rootAlias . '.Compra c');
      return $q;      
    }
}