<?php

/**
 * PresupuestoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PresupuestoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PresupuestoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Presupuesto');
    }
    
    public function retrieveConJoins(Doctrine_Query $q){
			$id = sfContext::getInstance()->getUser()->getGuardUser()->getId();
      $rootAlias = $q->getRootAlias();
			$q->leftJoin($rootAlias.'.Zona z');
			$q->leftJoin('z.UsuarioZona uz');			
			$q->andWhere('uz.usuario = '.$id);
      $q->orderBy($rootAlias. '.fecha desc');
      return $q;
    }
}