<?php

/**
 * PresupuestoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PresupuestoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PresupuestoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Presupuesto');
    }
}