<?php

/**
 * Presupuesto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    odontopc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Presupuesto extends BasePresupuesto
{

  public function SePuedeVender(){
    $det_presupuesto = $this->getDetalle();
    foreach ($det_presupuesto as $det) {
      if (!empty($det->nro_lote)) return true;
    }
    return false;
  }
	
}