<?php

/**
 * Producto2Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Producto2Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Producto2Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Producto2');
    }
}