<?php

/**
 * PromocionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PromocionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PromocionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Promocion');
    }
    
    public function getVigentes() {
			$q = Doctrine_Core::getTable('Promocion')->createQuery('q');
			$q->where('fecha_ini <= curdate()');
			$q->andWhere('(fecha_fin >= curdate() or fecha_fin is null)');
      $q->orderBy('fecha_ini desc');
      return $q->execute();
    }
}