<?php

/**
 * PromocionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PromocionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PromocionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Promocion');
    }
}