<?php

/**
 * ResumenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ResumenTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ResumenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Resumen');
    }
    
    function construct(){
        $this->setOption('orderBy','fecha DESC');
    }    
    
    public function retrieveConJoins(Doctrine_Query $q){
      $rootAlias = $q->getRootAlias();
      $q->leftJoin($rootAlias . '.Cliente c');
      $q->leftJoin($rootAlias . '.Lista l');
      $q->leftJoin($rootAlias . '.Detalle d');
      $q->leftJoin($rootAlias . '.Venta v');
      $q->leftJoin($rootAlias . '.Moneda m');
      $q->orderBy($rootAlias . '.fecha desc');
      return $q;
    }    
}
