<?php

/**
 * TipoCobroPagoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoCobroPagoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoCobroPagoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoCobroPago');
    }
}