<?php

/**
 * TipoFacturaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoFacturaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoFacturaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoFactura');
    }
}