<?php

/**
 * VentasZonaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VentasZonaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VentasZonaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VentasZona');
    }
}