<?php

/**
 * VtaFactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VtaFactTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VtaFactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VtaFact');
    }
    
    public function retrieve(Doctrine_Query $q){
      $rootAlias = $q->getRootAlias();
      $q->leftJoin($rootAlias.'.Producto p');
      $q->orderBy($rootAlias.'.producto_id asc');
      $q->addOrderBy($rootAlias.'.fecha asc');
      return $q;
    }
}