<?php

/**
 * ZonaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ZonaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ZonaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Zona');
    }
		
		public function getZonasUsuario(){
			$id = sfContext::getInstance()->getUser()->getGuardUser()->getId();
			$query = Doctrine_Core::getTable('Zona')
			->createQuery('q')
			->leftJoin('q.UsuarioZona uz')
			->andWhere('uz.usuario = '.$id)
			->orderBy('q.id ASC');
			$result = $query->execute();
			return $result;
		}	
}