generator:
  class: sfDoctrineGenerator
  param:
    model_class:           CobroResumen
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          cobro_resumen
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Cobros asociados a facturas
        display: [_cliente, _cobro, _fecha_cobro, _monto_cobro, Resumen, _fecha_fac, _monto_fac]
        object_actions: []
        actions:
          imprimir_pagina: {label: Imprimir Pagina}
          imprimir_todo: {label: Imprimir todo}
          excel_pagina: {label: Descargar Pagina}
          excel_todo: {label: Descargar Todo}
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
