# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/05-Factories
dev:
  mailer:
    param:      
      delivery_strategy: single_address
      #delivery_strategy: none
      delivery_address:  alfredochoternasty@gmail.com
      transport:
        class: Swift_SmtpTransport
        param:
          host: smtp.gmail.com
          port: 465
          encryption: ssl
          auth_mode: auth
          username: alfredochoternasty@gmail.com
          password: cham*3213
          
prod:
  logger:
    class:   sfNoLogger
    param:
      level:   err
      loggers: ~
  mailer:
    param:
      delivery_strategy: realtime
      transport:
        class: Swift_SmtpTransport
        param:
          host: smtp.gmail.com
          port: 465
          encryption: ssl
          auth_mode: auth
          username: implantesnti@gmail.com
          password: tomatepodrido

all:
  user:
    class: myUser
    param:
      timeout: 36000
  routing:
    class: sfPatternRouting
    param:
      generate_shortest_url:            false
      extra_parameters_as_query_string: true

  view_cache_manager:
    class: sfViewCacheManager
    param:
      cache_key_use_vary_headers: true
      cache_key_use_host_name:    true