generator:
  class: sfDoctrineGenerator
  param:
    model_class:           DetalleVenta
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          detalle_venta
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        Venta: {label: Factura}
      list:
        title: Detalle de Factura
        display: [Venta, _producto, _precio, cantidad, subtotal, iva,  _total]
        object_actions:
          _delete: ~
      filter:  ~
      form:    ~
      edit:    ~
      new:
        title: Nuevo Detalle de la Factura
