generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Cliente
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          cliente_registro
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        dni: {label: DNI, help: Solo números y sin puntos}
        cuit: {label: CUIT, help: Solo números}
        celular: {label: Nro. de Celular, help: Solo números}
        telefono: {label: Nro. de Teléfono Fijo, help: Solo números}
        domicilio: {help: Por favor indique ciudad y provincia}
        nro_matricula: {label: Nro. de Matrícula Profesional}
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:
        title: Por favor ingrese sus datos
        display: [dni, cuit, condicionfiscal_id, apellido, nombre, domicilio, nro_matricula, telefono, celular, email]
        actions:
          _save: ~
          _list: ~
