generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ClienteUltimaCompra
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          cliente_ultima_compra
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        fecha: {label: Ultima compra, date_format: dd/MM/yyyy }
      list:
        max_per_page: 20
        title: Ultima compra por cliente
        display: [Zona, apellido, nombre, fecha, telefono, celular, email]
        object_actions:
          factura: ~
        actions:
          imprimir_pagina: {label: Imprimir Pagina}
          imprimir_todo: {label: Imprimir todo}
          excel_pagina: {label: Descargar Pagina}
          excel_todo: {label: Descargar Todo}
      filter:
        display: [zona_id, apellido, nombre, fecha]
      form:    ~
      edit:    ~
      new:     ~
      show:
        display: [apellido, nombre, fecha, telefono, celular, email]
