generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Zona
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          zona
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: ABM de Zonas
        display: [nombre, Cliente]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
