generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ClienteSaldo
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          cliente_saldos
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        apellido: {label: Apellido}
        nombre: {label: Nombre}
        mayor: {label: Saldo mayor que, help: numero sin puntos ni comas por ej 5000}
      list:
        table_method: retrieveConJoins
        max_per_page: 50
        title: Listado de Saldos  
        display: [apellido, nombre, _saldo]
        object_actions: []
        batch_actions: []
        actions:
          imprimir_pagina: {label: Imprimir página}
          imprimir_todo: {label: Imprimir todo}
      filter:
        display: [apellido, moneda_id, zona_id, mayor]
      form:    ~
      edit:    ~
      new:     ~
      show:
        display: [apellido, nombre, saldo]