generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ClienteSaldo
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          cliente_saldos
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        max_per_page: 50
        title: Listado de Saldos  
        display: [tipo_cliente, apellido, nombre, moneda, _saldo]
        object_actions: []
        batch_actions: []
        actions:
          imprimir: {label: Imprimir página}
      filter:
        display: [apellido, nombre, moneda, mayor]
      form:    ~
      edit:    ~
      new:     ~
