generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Pago
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          pago
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        fecha: { date_format: dd/MM/yyyy }
      list:
        title: Pagos a Proveedores
        display: [Proveedor, fecha, monto, moneda_id, Tipo, Banco, numero, observacion]
        object_actions:
          _delete: {label: Eliminar}
          _edit: {label: Modificar}
        actions:
          _new: {label: Cargar Nuevo Pago}
      filter:
        display: [proveedor_id, fecha, tipo_id, banco_id, numero]
      form:
        display: [proveedor_id, fecha, tipo_id, moneda_id, monto, banco_id, numero, comprobante, observacion]
      edit:
        title: Modificar Pago a Proveedor
      new:
        title: Nuevo Pago a Proveedor
