generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ClienteUltimaCompra
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          cliente_ultima_compra
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        fecha: { date_format: dd/MM/yyyy }
      list:
        title: Ultima compra por clientes
        display: [apellido, nombre, fecha]
        object_actions:
          detalle: ~
      filter:
        display: [cliente_id, fecha]
      form:    ~
      edit:    ~
      new:     ~
