generator:
  class: sfDoctrineGenerator
  param:
    model_class:           CtaCteProv
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          cta_cte_prov
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        fecha: { date_format: dd/MM/yyyy }
      list:
        max_per_page: 9999
        table_method: retrieveCtaConProv
        title: Listado de Cuenta Corriente de Proveedor
        sort: [fecha, asc]
        display: [_concepto, fecha, Proveedor, Cuenta, debe, haber, _saldo]
        object_actions: {}
        batch_actions: {}
        actions:
          imprimir: {label: Imprimir}
      filter:
        display: [fecha, cuenta_id, proveedor_id]
      form:    ~
      edit:    ~
      new:     ~