generator:
  class: sfDoctrineGenerator
  param:
    model_class:           DetFactCompra
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          det_fact_compra
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        grupoprod_id: { label: Grupo}
      list:
        title: Detalle de Factura de Compra
        display: [Factura, _producto, _precio, cantidad, subtotal, iva, _total]
        object_actions:
          _delete: {label: Eliminar}
          _edit: {label: Modificar}
      filter:  ~
      form:
        actions:
          _list: {label: Volver}
          _save: {label: Guardar}
          _save_and_add: {label: Guardar y Agregar Otro}
      edit:
        title: Modificar Detalle de Factura de Compra
      new:
        title: Nuevo Detalle de Factura de Compra
