generator:
  class: sfDoctrineGenerator
  param:
    model_class:           FactCompra
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          fact_compra
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        fecha: { date_format: dd/MM/yyyy }
        tipofactura_id: { label: Comprobante }
      list:
        title: Facturas de Compras
        display: [numero, Tipofactura, fecha, Proveedor, _total, observacion]
        object_actions:
          _delete: {label: Eliminar}
          _edit: {label: Modificar}
          detalle: {label: Ver Detalle}
      filter:  ~
      form:
        actions:
          _list: {label: Volver}
          _save: {label: Guardar y Agregar Detalle}      
      edit:
        title: Modificar Factura de Compra
      new:
        title: Nueva Factura de Compra
