generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ListadoCobros
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          listado_cobros
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        fecha: { date_format: dd/MM/yyyy }
      list:
        title: Listado de Cobros
        max_per_page: 50
        display: [Zona, fecha, Cliente, tipo_cobro, _monto, observacion]
        object_actions: []
        batch_actions: []
        actions:
          imprimir_pagina: {label: Imprimir Pagina}
          imprimir_todo: {label: Imprimir todo}
          excel_pagina: {label: Descargar Pagina}
          excel_todo: {label: Descargar Todo}
      filter:
        display: [fecha, cliente, tipo_cobro, zona_id]
      form:    ~
      edit:    ~
      new:     ~
      show:
        display: [Zona, fecha, Cliente, tipo_cobro, _monto, observacion]