<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/02/18 03:55:37

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=ntiimplantes_db',
  'username' => 'root',
  'password' => NULL,
  'attributes' => 
  array (
    'default_table_type' => 'MyISAM',
    'default_table_collate' => 'utf8_unicode_ci',
    'default_table_charset' => 'utf8',
  ),
  'name' => 'doctrine',
)),);
