<?php
// auto-generated by sfSecurityConfigHandler
// date: 2015/02/21 15:37:01
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'datos',
        2 => 'traza',
      ),
    ),
  ),
);
