generator:
  class: sfDoctrineGenerator
  param:
    model_class:           DetallePresupuesto
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          detalle_presupuesto
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      fields: ~
      list:
        table_method: retrieveConJoins
        title: Detalle del presupuesto
        max_per_page: 9999
        display: [Producto, _precio, cantidad, _descuento, _sub_total, _iva, _total]
        object_actions:
          _delete: {label: Eliminar}
          _edit: {label: Modificar}
        actions:
          _new: {label: Nuevo}
          imprimir: {label: Imprimir}
      filter: {}
      form: ~
      edit:
        title: Modificar detalle del presupuesto
        display: [producto_id, precio, cantidad, descuento, sub_total, iva, total]
      new:
        title: Nuevo detalle del presupuesto
        display: [producto_id, precio, cantidad, descuento, sub_total, iva, total]