generator:
  class: sfDoctrineGenerator
  param:
    model_class:           CursoInscripcion
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          curso_inscripcion
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        fecha: { label: Fecha Insc., date_format: dd/MM/yyyy }
        tipo_insc_id: {label: Tipo Inscripcion}
      list:
        table_method: retrievePorZona
        title: Insacriptos a Cursos
        display: [_zona, Curso, dni, nombre, localidad, telefono, correo, fecha, _visto, _asistio, _pago]
        actions:
          imprimir_pagina: {label: Imprimir Pagina}
          imprimir_todo: {label: Imprimir todo}
          excel_pagina: {label: Descargar Pagina}
          excel_todo: {label: Descargar todo}
        object_actions:
          _visto:
          _asistio:
          _pago:
      filter:
        display: [curso_id, dni, nombre, localidad, telefono, correo, fecha, visto, asistio, pago]
      form: ~
      edit:
        title: Editar Inscripcion
        display: [curso_id, dni, nombre, localidad, telefono, correo, comentario]
      new:
        title: Nueva Inscripcion
        display: [curso_id, dni, nombre, localidad, telefono, correo, comentario]