default:
  http_metas:
    content-type: text/html
  stylesheets:    [inicio.css, chosen.css, colorpicker.css]
  javascripts:    [chosen.jquery.min.js, funciones_ajax.js]
  has_layout:     true
  layout:         layout