generator:
  class: sfDoctrineGenerator
  param:
    model_class:           DetalleCompra
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          detalle_compra
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Detalle de Compra
        max_per_page: 999
        display: [Compra, Producto, nro_lote, fecha_vto, _precio, cantidad, sub_total, iva, _total]
        object_actions:
          _delete: ~
        batch_actions: {}       
        actions:
          _new: ~
          imprimir: {label: Imprimir}
      filter:  ~
      form:    ~
      edit:
        title: Modificar Detalle de la compra %%Compra%%
      new:
        title: Nuevo Detalle de la compra %%Compra%%
        display: [producto_id, nro_lote, fecha_vto, precio, cantidad, sub_total, iva, total, observacion]
