generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Traza2
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          traza2
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        Producto2: { label: Producto }
        nro_lote: { label: Lote }
        nro_venta: { label: Venta }
        numero_compra: { label: Compra }
        fecha_venta: { date_format: dd/MM/yyyy }
        fecha_compra: { date_format: dd/MM/yyyy }
      list:
        table_method: retrieveConJoins
        title: Traza de Productos
        display: [Producto2, cant_vendida, nro_lote, fecha_venta, Cliente]
        max_per_page: 20
        object_actions:
          _delete: {label: Eliminar}
          _edit: {label: Modificar}
        actions:
          _new: {label: Nuevo}
          imprimir: {label: Imprimir}
      filter:
        display: [producto_id, cant_vendida, nro_lote, fecha_venta, cliente_id]
      form:    ~
      edit:
        title: Modificar Traza
        display: [producto_id, cant_vendida, nro_lote, fecha_venta, cliente_id]
      new:
        title: Nueva Traza
        display: [producto_id, cant_vendida, nro_lote, fecha_venta, cliente_id]
