generator:
  class: sfDoctrineGenerator
  param:
    model_class:           DescuentoZona
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          descuento_zona
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        grupoprod_id: {label: Grupo}
        Grupoprod: {label: Grupo}
        porc_desc: {label: Porcentaje}
        zona_id: {label: Zona}
        Zona: {label: Zona}
      list:
        title: Comisiones por Zona
        display: [Producto, Grupoprod, porc_desc, Zona]
        object_actions:
            _edit: ~
            _delete: ~
        actions:
            _new: {label: Nuevo}
      filter:  ~
      form:
        display: [producto_id, grupoprod_id, porc_desc, zona_id]
      edit:
        title: Modificar
      new:
        title: Nuevo
