generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ListadoCompras
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          listado_compras
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        compra_id: { label: compra}
        fecha: { date_format: dd/MM/yyyy }
        cantidad: { label: Cant.}
        grupoprod_id: {label: Grupo}
        nro_lote: {label: Lote}
      list:
        title: Listado de Compras
        display: [Zona, Proveedor, Compra, fecha, Producto, cantidad, nro_lote]
        max_per_page: 50
        object_actions: []
        batch_actions: []
        actions:
          imprimir: ~        
      filter:
        display: [proveedor_id, fecha, producto_id, nro_lote, zona_id]
      form:    ~
      edit:    ~
      new:     ~
