generator:
  class: sfDoctrineGenerator
  param:
    model_class:           UsuarioZona
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          usuario_zona
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: ABM de Usuarios x Zonas
        display: [Zona, Usuario]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
