generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ControlStock
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          control_stock
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        Grupo: { label: Grupo}
        grupoprod_id: { label: Grupo}
        Producto: { label: Producto}
        nro_lote: { label: Lote}
        cant_comprada: { label:  Comprados}
        cant_vendida: { label: Vendidos }
        stock_guardado: { label: Stock Guardado}
        ult_venta: {label: Ultima Venta}
      list:
        table_method: retrieveConJoins
        title: Listado de Control de Stock
        display: [Grupo, Producto, Zona, nro_lote, comprados, _vendidos, stock_guardado, ult_venta]
        object_actions: []
        batch_actions: []
        actions:
          imprimir_todo: ~     
          imprimir_pagina: ~     
      filter:
        display: [grupoprod_id, producto_id, nro_lote, zona_id, ult_venta]
      form:    ~
      edit:    ~
      new:     ~
