generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ControlStock
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          control_stock
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        Grupo: { label: Grupo}
        grupoprod_id: { label: Grupo}
        Producto: { label: Producto}
        nro_lote: { label: Lote}
        cant_comprada: { label:  Comprados}
        cant_vendida: { label: Vendidos }
        stock: { label: Stock }
      list:
        table_method: retrieveConJoins
        title: Listado de Control de Stock
        display: [Proveedor, Grupo, Producto, nro_lote, comprados, _vendidos, _stock_actual]
        object_actions: []
        batch_actions: []
        actions:
          imprimir: ~     
      filter:
        display: [proveedor_id, grupoprod_id, producto_id, nro_lote]
      form:    ~
      edit:    ~
      new:     ~
