generator:
  class: sfDoctrineGenerator
  param:
    model_class:           CursoMailEnviado
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          curso_mail_enviado
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        fecha: {date_format: dd/MM/yyyy hh:mm}
        tipo_envio: {label: A quien enviar?}
        sfGuardUser: {label: Usuario Envio}
      list: 
        table_method: retrieveConJoins
        title: Emails con info de cursos enviados
        display: [Curso, cliente, e_mail, fecha, sfGuardUser]
        object_actions: []
        batch_actions: []
      filter:
        display: [curso_id, cliente_id, e_mail]
      form:    ~
      edit:    ~
      new:
        title: Enviar email con info de curso
        display: [curso_id, tipo_envio, cliente_id, e_mail]
