generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Resumen
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          resumen_usuvta
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        sfGuardUser: {label: Usuario}
      list:
        title: Ventas por Usuario
        max_per_page: 20
        display: [TipoFactura, nro_factura, fecha, Cliente, sfGuardUser]
        actions:
          imprimir_pagina: {label: Imprimir Pagina}
          imprimir_todo: {label: Imprimir todo}
          excel_pagina: {label: Descargar Pagina}
          excel_todo: {label: Descargar Todo}
        object_actions: []
        batch_actions: []
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
      show:
        display: [TipoFactura, nro_factura, fecha, Cliente, sfGuardUser]
