generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Grupoprod2
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          grupoprod2
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Grupo de productos
      filter:  ~
      form:    ~
      edit:
        title: Modificar Grupo
      new:
        title: Nuevo Grupo
