generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TipoVenta
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tipo_venta
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Tipos de Ventas
        display: [nombre, porc_recargo]
        object_actions:
          _delete: {label: Eliminar}
          _edit: {label: Modificar}
        actions:
            _new: {label: Nuevo}
      filter:  ~
      form:    ~
      edit:
        title: Modificar Tipo de Venta
      new:
        title: Nuevo Tipo de Venta
