generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Pedido
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          pedido
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        id: { label: Nro. }
        fecha: { date_format: dd/MM/yyyy }
        fecha_venta: { label: Vendido, date_format: dd/MM/yyyy }
      list:
        title: Pedidos Pendientes
        max_per_page: 30
        display: [id, fecha, fecha_venta]
        object_actions:
          _delete: ~
          detalle: {label: Ver Detalle}
        actions:
          _new: {label: Nuevo pedido}
      filter:
        display: [fecha]
      form:
      edit:
        title: Datos extra del pedido
        display: [direccion_entrega, observacion]
        actions:
          _save: ~
      new:     ~
