generator:
  class: sfDoctrineGenerator
  param:
    model_class:           localidad
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          localidad
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Administraci&oacute;n de Localidades
        display: [nombre, Provincia]
        object_actions:
          _delete: {label: Eliminar}
          _edit: {label: Modificar}
      filter:  ~
      form:    ~
      edit:
        title: Modificar Localidad
      new:
        title: Nueva Localidad
