generator:
  class: sfDoctrineGenerator
  param:
    model_class:           DescuentoZona
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          descuento_zona
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        asignado: {label: Asignado a}
        comision: {label: Comision}
        porc_desc: {label: Comision}
      list:
        title: Comisiones por Zona
        display: [Zona, _asignado, _nombre, _comision]
        object_actions:
            _delete: ~
        actions:
            _new: {label: Nuevo}
      filter:
        display: [cliente_id, grupoprod_id, producto_id, porc_desc, zona_id]
      form:
        display: [operacion, cliente_id, grupoprod_id, producto_id, porc_desc, zona_id]
      edit:
        title: Modificar
      new:
        title: Nuevo
