generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Producto
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          stock
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: {}
      fields:  ~
      list:
        table_method: retrieveSinInternos
        title: Listado de Stock
        display: [Grupo, nombre, l.nro_lote, minimo_stock]
        object_actions: {}
        batch_actions: {}
        actions:
          imprimir: {label: Imprimir}
      filter:
        display: [nombre, grupoprod_id]
      form:    ~
      edit:    ~
      new:     ~
