generator:
  class: sfDoctrineGenerator
  param:
    model_class:           LoteAjuste
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          lote_ajuste
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        SfGuardUser: {label: Usuario}
        nro_lote: {label: Lote}
      list:
        title: Ajustes de Stock
        display: [Zona, fecha, Producto, nro_lote, cantidad, observacion, SfGuardUser]
        actions:
          _new: {label: Nuevo}
        object_actions:
          imprimir_pagina: {label: Imprimir Pagina}
          imprimir_todo: {label: Imprimir todo}
          excel_pagina: {label: Descargar Pagina}
          excel_todo: {label: Descargar Todo}
        batch_actions: []
      filter:
        display: [fecha, zona_id, producto_id, nro_lote]
      form:
        display: [fecha, zona_id, producto_id, nro_lote, cantidad, observacion, usuario_id]
      edit:    ~
      new:
        title: Nuevo Ajuste
      show:
        display: [Zona, fecha, Producto, nro_lote, cantidad, observacion, SfGuardUser]
