generator:
  class: sfDoctrineGenerator
  param:
    model_class:           LoteAjuste
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          lote_ajuste
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        SfGuardUser: {label: Usuario}
        nro_lote: {label: Lote}
      list:
        title: Ajustes de Stock
        display: [Zona, fecha, Producto, nro_lote, cantidad, observacion, SfGuardUser]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
